CREATE TABLE IF NOT EXISTS users(
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(75) NOT NULL,
    email VARCHAR(75) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS peoples(
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(75) NOT NULL,
    age INT NOT NULL
);